### ISSUE TITLE
Hello! need guidance

### ISSUE THREAD

**Issue by fisherman1717** [Yuyuko-sama/Xigncode-bypass#1]
Hello Yuyuko-sama, can i ask what this xigncode bypass does?
I see that it is an addon mod that can be applied to toolbox.
Does it help with reducing ping or latency and increase your DPS a lot?

**Comment by Yuyuko-sama** [comment]
the only thing it can do is stop xigncode running when client launcher.exe start.
and as i know，there's no mod can do like reduce physical pings.
the only mod witch can helps u increas Dps under high pings is SP mod
